modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
[[mods]]
modId="end_respawn_anchor"
version="1.0"
displayName="EndRespawnAnchor"
authors="Mikn"
description='''
This mod adds a block like the respawn anchor.
When you use this block, you will respawn at the end as you die in the end.
but when you die in the dimension where your respawn point was, you will respawn there.
This mod adds one file [World Save Data]/data/end_respawn_anchor.json
So, if you remove this mod, you should remove the file.
'''
[[dependencies.end_respawn_anchor]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"
[[dependencies.end_respawn_anchor]]
modId="minecraft"
mandatory=true
versionRange="[1.18.1,1.19)"
ordering="NONE"
side="BOTH"