modLoader = "javafml"
loaderVersion = "{loader_version_range}"
license = "MIT License"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
credits = "Credit for brilliant textures goes to rosieholstein"
description = '''
The EndRespawnAnchor is used to respawn in the End.
Remember you will always respawn in the End wherever you die.
'''
[[dependencies.end_respawn_anchor]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.end_respawn_anchor]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[mixins]]
config = "end_respawn_anchor.mixins.json"
